### ISSUE TITLE
Даделать

### ISSUE THREAD

**Issue by puphem** [RARKA228/Vizprog_lab05#2]
При закрытии программы на крестик вывести окно с сохранением, такое же, которое какое при несохраненном файле когда мы хотим новый создать поняли да? усекли чтобы к дедлайну шестой было исправлено готово лично проверю посмотрю че да как приём

**Comment by puphem** [comment]
![конь с бокалом ржака](https://github.com/user-attachments/assets/d1c68a5b-e287-48de-8b9a-ef3647e5a826)
cheers

**Comment by RARKA228** [comment]
тупой еблан

**Comment by RARKA228** [comment]
[Uploading Lab2_1__3.pdf…]()
